version: "3.3"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.10
    ports:
      - "8086:8086"
    volumes: 
      - kelvin-influxdb:/var/lib/influxdb
    restart: unless-stopped
  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.3
    depends_on:
      - influxdb
    ports: 
      - "3000:3000"
    volumes: 
      - kelvin-grafana:/var/lib/grafana
    restart: unless-stopped
  kelvin:
    container_name: kelvin-hub
    image: ghcr.io/kelvinthermostat/hub:latest
    depends_on: 
      - influxdb
    ports:
      - "5000:5000"
    volumes: 
      - kelvin-hub:/app/kelvin/data
    restart: unless-stopped
    environment:
      - influxdb_host=influxdb
      - influxdb_database=kelvin
      - thermostat_url=http://192.168.68.200
volumes:
  kelvin-hub: 
  kelvin-grafana: 
  kelvin-influxdb: 
