version: "3.3"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes: 
      - kelvin-influxdb:/var/lib/influxdb
    restart: unless-stopped
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    ports: 
      - "3000:3000"
    volumes: 
      - kelvin-grafana:/var/lib/grafana
    restart: unless-stopped
  kelvin:
    container_name: kelvin-hub
    image: kelvinthermostat/hub:latest
    depends_on: 
      - influxdb
    ports:
      - "5000:5000"
    volumes: 
      - kelvin-hub:/home/kelvin/data
    restart: unless-stopped
    environment:
      - TZ='Europe/Dublin'
      - influxdb_host=influxdb
      - influxdb_database=kelvin
      - sensor_url=http://192.168.68.201
      - heater_switch_url=http://192.168.68.200
volumes:
  kelvin-hub: 
  kelvin-grafana: 
  kelvin-influxdb: 
